version: 2.1
orbs:
  protobuf: izumin5210/protobuf@0.1.0
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # GRPC CPP is built from source. Try to restore the latest release from cache.
      - run:
          name: "Determine latest GRPC release"
          command: |
            curl -L https://grpc.io/release >> latest_grpc_release.txt
      - restore_cache:
          keys:
            - grpc-cpp-{{ checksum "latest_grpc_release.txt" }}

      - protobuf/install

      - run:
          name: "Install GRPC"
          command: |
            if [ ! -d grpc ]; then
            git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
            cd grpc
            git submodule update --init
            make
            fi

      - run: mkdir -p generated
      - run:
          name: "Compile Protocol Buffers Models"
          command: |
            protoc models/*.proto --proto_path=./models/ --cpp_out ./generated/

      - run:
          name: "Compile GRPC Protocol Buffers Services"
          command: |
            protoc -I ./services/ -I ./models/ --grpc_out=./generated --plugin=protoc-gen-grpc=grpc/bins/opt/grpc_cpp_plugin ./services/*.proto ./models/*.proto

      # Save built GRPC artifacts to cache.
      - save_cache:
          key: grpc-cpp-{{ checksum "latest_grpc_release.txt" }}
          paths:
            - grpc/
